font_family family="DroidSansM Nerd Font Mono"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14.0

window_padding_width 5 20
placement_strategy center
enabled_layouts splits,stack
window_border_width 1
draw_minimal_borders yes
active_border_color #565f89
inactive_border_color #1f1f28
inactive_text_alpha -0.60

background_opacity 0.70
background_blur 20
dynamic_background_opacity yes
hide_window_decorations titlebar-only
macos_titlebar_color background

tab_bar_edge top
tab_bar_min_tabs 1
tab_bar_style separator
tab_separator " "
tab_title_max_length 24
tab_bar_background #1f1f28
active_tab_foreground #c5c9c5
active_tab_background #2a2a37
active_tab_font_style bold
inactive_tab_foreground #565f89
inactive_tab_background #1f1f28
inactive_tab_font_style normal
tab_title_template "{custom}"

cursor_shape block
mouse_hide_wait -1
enable_audio_bell no
window_alert_on_bell no
confirm_os_window_close -1
macos_option_as_alt yes

map cmd+ctrl+[ set_background_opacity -0.05
map cmd+ctrl+] set_background_opacity +0.05

map cmd+d launch --location=vsplit --cwd=current
map cmd+shift+d launch --location=hsplit --cwd=current
map cmd+[ previous_window
map cmd+] next_window
map cmd+alt+h resize_window narrower 5
map cmd+alt+j resize_window taller 5
map cmd+alt+k resize_window shorter 5
map cmd+alt+l resize_window wider 5
map cmd+w close_window_with_confirmation
map cmd+z toggle_layout stack
map cmd+enter toggle_fullscreen

map cmd+t new_tab_with_cwd
map cmd+shift+w close_tab

map cmd+equal change_font_size all +1.0
map cmd+plus change_font_size all +1.0
map cmd+minus change_font_size all -1.0
map cmd+0 change_font_size all 0

include themes/black-metal-bathory.conf
