return {
	{
		"sindrets/diffview.nvim",
		dependencies = { "nvim-lua/plenary.nvim" },
		cmd = { "DiffviewOpen", "DiffviewFileHistory", "DiffviewClose", "DiffviewToggleFiles", "DiffviewFocusFiles" },
		config = function()
			require("diffview").setup({
				diff_binaries = false,
				enhanced_diff_hl = true,
				git_cmd = { "git" },
				hg_cmd = { "hg" },
				diff_algorithm = "histogram",
				use_icons = true,
				show_help_hints = true,
				watch_index = true,
				icons = {
					folder_closed = "",
					folder_open = "",
				},
				signs = {
					fold_closed = "",
					fold_open = "",
					done = "✓",
				},
				view = {
					default = {
						layout = "diff2_horizontal",
						winbar_info = false,
					},
					merge_tool = {
						layout = "diff3_horizontal",
						disable_diagnostics = true,
						winbar_info = true,
					},
					file_history = {
						layout = "diff2_horizontal",
						winbar_info = false,
					},
				},
				file_panel = {
					listing_style = "tree",
					tree_options = {
						flatten_dirs = true,
						folder_statuses = "only_folded",
					},
					win_config = {
						position = "left",
						width = 35,
						win_opts = {},
					},
				},
				file_history_panel = {
					log_options = {
						git = {
							single_file = {
								diff_merges = "combined",
							},
							multi_file = {
								diff_merges = "first-parent",
							},
						},
						hg = {
							single_file = {},
							multi_file = {},
						},
					},
					win_config = {
						position = "bottom",
						height = 16,
						win_opts = {},
					},
				},
				commit_log_panel = {
					win_config = {},
				},
				default_args = {
					DiffviewOpen = {},
					DiffviewFileHistory = {},
				},
				hooks = {},
				keymaps = {
					disable_defaults = false,
					view = {
						{
							"n",
							"<tab>",
							"<cmd>lua require('diffview.actions').select_next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"<s-tab>",
							"<cmd>lua require('diffview.actions').select_prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"gf",
							"<cmd>lua require('diffview.actions').goto_file_edit()<CR>",
							{ desc = "Open file in current window" },
						},
						{
							"n",
							"<C-w><C-f>",
							"<cmd>lua require('diffview.actions').goto_file_split()<CR>",
							{ desc = "Open file in split" },
						},
						{
							"n",
							"<C-w>gf",
							"<cmd>lua require('diffview.actions').goto_file_tab()<CR>",
							{ desc = "Open file in new tab" },
						},
						{
							"n",
							"<leader>df",
							"<cmd>lua require('diffview.actions').focus_files()<CR>",
							{ desc = "Focus file panel" },
						},
						{
							"n",
							"<leader>b",
							"<cmd>lua require('diffview.actions').toggle_files()<CR>",
							{ desc = "Toggle file panel" },
						},
						{
							"n",
							"g<C-x>",
							"<cmd>lua require('diffview.actions').cycle_layout()<CR>",
							{ desc = "Cycle layout" },
						},
						{
							"n",
							"[x",
							"<cmd>lua require('diffview.actions').prev_conflict()<CR>",
							{ desc = "Previous conflict" },
						},
						{
							"n",
							"]x",
							"<cmd>lua require('diffview.actions').next_conflict()<CR>",
							{ desc = "Next conflict" },
						},
						{
							"n",
							"<leader>co",
							"<cmd>lua require('diffview.actions').conflict_choose('ours')<CR>",
							{ desc = "Choose OURS" },
						},
						{
							"n",
							"<leader>ct",
							"<cmd>lua require('diffview.actions').conflict_choose('theirs')<CR>",
							{ desc = "Choose THEIRS" },
						},
						{
							"n",
							"<leader>cb",
							"<cmd>lua require('diffview.actions').conflict_choose('base')<CR>",
							{ desc = "Choose BASE" },
						},
						{
							"n",
							"<leader>ca",
							"<cmd>lua require('diffview.actions').conflict_choose('all')<CR>",
							{ desc = "Choose ALL" },
						},
						{
							"n",
							"dx",
							"<cmd>lua require('diffview.actions').conflict_choose('none')<CR>",
							{ desc = "Delete conflict" },
						},
						{
							"n",
							"<leader>cO",
							"<cmd>lua require('diffview.actions').conflict_choose_all('ours')<CR>",
							{ desc = "Choose all OURS" },
						},
						{
							"n",
							"<leader>cT",
							"<cmd>lua require('diffview.actions').conflict_choose_all('theirs')<CR>",
							{ desc = "Choose all THEIRS" },
						},
						{
							"n",
							"<leader>cB",
							"<cmd>lua require('diffview.actions').conflict_choose_all('base')<CR>",
							{ desc = "Choose all BASE" },
						},
						{
							"n",
							"<leader>cA",
							"<cmd>lua require('diffview.actions').conflict_choose_all('all')<CR>",
							{ desc = "Choose all ALL" },
						},
						{
							"n",
							"dX",
							"<cmd>lua require('diffview.actions').conflict_choose_all('none')<CR>",
							{ desc = "Delete all conflicts" },
						},
					},
					diff_view = {
						{
							"n",
							"<tab>",
							"<cmd>lua require('diffview.actions').select_next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"<s-tab>",
							"<cmd>lua require('diffview.actions').select_prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"gf",
							"<cmd>lua require('diffview.actions').goto_file_edit()<CR>",
							{ desc = "Open file in current window" },
						},
						{
							"n",
							"<C-w><C-f>",
							"<cmd>lua require('diffview.actions').goto_file_split()<CR>",
							{ desc = "Open file in split" },
						},
						{
							"n",
							"<C-w>gf",
							"<cmd>lua require('diffview.actions').goto_file_tab()<CR>",
							{ desc = "Open file in new tab" },
						},
						{
							"n",
							"<leader>df",
							"<cmd>lua require('diffview.actions').focus_files()<CR>",
							{ desc = "Focus file panel" },
						},
						{
							"n",
							"<leader>b",
							"<cmd>lua require('diffview.actions').toggle_files()<CR>",
							{ desc = "Toggle file panel" },
						},
						{
							"n",
							"g<C-x>",
							"<cmd>lua require('diffview.actions').cycle_layout()<CR>",
							{ desc = "Cycle layout" },
						},
						{
							"n",
							"[x",
							"<cmd>lua require('diffview.actions').prev_conflict()<CR>",
							{ desc = "Previous conflict" },
						},
						{
							"n",
							"]x",
							"<cmd>lua require('diffview.actions').next_conflict()<CR>",
							{ desc = "Next conflict" },
						},
						{
							"n",
							"<leader>co",
							"<cmd>lua require('diffview.actions').conflict_choose('ours')<CR>",
							{ desc = "Choose OURS" },
						},
						{
							"n",
							"<leader>ct",
							"<cmd>lua require('diffview.actions').conflict_choose('theirs')<CR>",
							{ desc = "Choose THEIRS" },
						},
						{
							"n",
							"<leader>cb",
							"<cmd>lua require('diffview.actions').conflict_choose('base')<CR>",
							{ desc = "Choose BASE" },
						},
						{
							"n",
							"<leader>ca",
							"<cmd>lua require('diffview.actions').conflict_choose('all')<CR>",
							{ desc = "Choose ALL" },
						},
						{
							"n",
							"dx",
							"<cmd>lua require('diffview.actions').conflict_choose('none')<CR>",
							{ desc = "Delete conflict" },
						},
						{
							"n",
							"<leader>cO",
							"<cmd>lua require('diffview.actions').conflict_choose_all('ours')<CR>",
							{ desc = "Choose all OURS" },
						},
						{
							"n",
							"<leader>cT",
							"<cmd>lua require('diffview.actions').conflict_choose_all('theirs')<CR>",
							{ desc = "Choose all THEIRS" },
						},
						{
							"n",
							"<leader>cB",
							"<cmd>lua require('diffview.actions').conflict_choose_all('base')<CR>",
							{ desc = "Choose all BASE" },
						},
						{
							"n",
							"<leader>cA",
							"<cmd>lua require('diffview.actions').conflict_choose_all('all')<CR>",
							{ desc = "Choose all ALL" },
						},
						{
							"n",
							"dX",
							"<cmd>lua require('diffview.actions').conflict_choose_all('none')<CR>",
							{ desc = "Delete all conflicts" },
						},
					},
					file_panel = {
						{
							"n",
							"j",
							"<cmd>lua require('diffview.actions').next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"<down>",
							"<cmd>lua require('diffview.actions').next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"k",
							"<cmd>lua require('diffview.actions').prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"<up>",
							"<cmd>lua require('diffview.actions').prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"<cr>",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"o",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"l",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"<2-LeftMouse>",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"-",
							"<cmd>lua require('diffview.actions').toggle_stage_entry()<CR>",
							{ desc = "Stage/unstage" },
						},
						{
							"n",
							"s",
							"<cmd>lua require('diffview.actions').toggle_stage_entry()<CR>",
							{ desc = "Stage/unstage" },
						},
						{
							"n",
							"S",
							"<cmd>lua require('diffview.actions').stage_all()<CR>",
							{ desc = "Stage all" },
						},
						{
							"n",
							"U",
							"<cmd>lua require('diffview.actions').unstage_all()<CR>",
							{ desc = "Unstage all" },
						},
						{
							"n",
							"X",
							"<cmd>lua require('diffview.actions').restore_entry()<CR>",
							{ desc = "Restore entry" },
						},
						{
							"n",
							"L",
							"<cmd>lua require('diffview.actions').open_commit_log()<CR>",
							{ desc = "Open commit log" },
						},
						{
							"n",
							"g<C-x>",
							"<cmd>lua require('diffview.actions').cycle_layout()<CR>",
							{ desc = "Cycle layout" },
						},
						{
							"n",
							"zo",
							"<cmd>lua require('diffview.actions').open_fold()<CR>",
							{ desc = "Open fold" },
						},
						{
							"n",
							"h",
							"<cmd>lua require('diffview.actions').close_fold()<CR>",
							{ desc = "Close fold" },
						},
						{
							"n",
							"zc",
							"<cmd>lua require('diffview.actions').close_fold()<CR>",
							{ desc = "Close fold" },
						},
						{
							"n",
							"za",
							"<cmd>lua require('diffview.actions').toggle_fold()<CR>",
							{ desc = "Toggle fold" },
						},
						{
							"n",
							"zR",
							"<cmd>lua require('diffview.actions').open_all_folds()<CR>",
							{ desc = "Open all folds" },
						},
						{
							"n",
							"zM",
							"<cmd>lua require('diffview.actions').close_all_folds()<CR>",
							{ desc = "Close all folds" },
						},
						{
							"n",
							"<c-b>",
							"<cmd>lua require('diffview.actions').scroll_view(-0.25)<CR>",
							{ desc = "Scroll up" },
						},
						{
							"n",
							"<c-f>",
							"<cmd>lua require('diffview.actions').scroll_view(0.25)<CR>",
							{ desc = "Scroll down" },
						},
						{
							"n",
							"<tab>",
							"<cmd>lua require('diffview.actions').select_next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"<s-tab>",
							"<cmd>lua require('diffview.actions').select_prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"gf",
							"<cmd>lua require('diffview.actions').goto_file_edit()<CR>",
							{ desc = "Open file in current window" },
						},
						{
							"n",
							"<C-w><C-f>",
							"<cmd>lua require('diffview.actions').goto_file_split()<CR>",
							{ desc = "Open file in split" },
						},
						{
							"n",
							"<C-w>gf",
							"<cmd>lua require('diffview.actions').goto_file_tab()<CR>",
							{ desc = "Open file in new tab" },
						},
						{
							"n",
							"i",
							"<cmd>lua require('diffview.actions').listing_style()<CR>",
							{ desc = "Toggle list style" },
						},
						{
							"n",
							"f",
							"<cmd>lua require('diffview.actions').toggle_flatten_dirs()<CR>",
							{ desc = "Toggle flatten" },
						},
						{
							"n",
							"R",
							"<cmd>lua require('diffview.actions').refresh_files()<CR>",
							{ desc = "Refresh files" },
						},
						{
							"n",
							"<leader>df",
							"<cmd>lua require('diffview.actions').focus_files()<CR>",
							{ desc = "Focus file panel" },
						},
						{
							"n",
							"<leader>b",
							"<cmd>lua require('diffview.actions').toggle_files()<CR>",
							{ desc = "Toggle file panel" },
						},
						{
							"n",
							"g<C-x>",
							"<cmd>lua require('diffview.actions').cycle_layout()<CR>",
							{ desc = "Cycle layout" },
						},
						{
							"n",
							"[x",
							"<cmd>lua require('diffview.actions').prev_conflict()<CR>",
							{ desc = "Previous conflict" },
						},
						{
							"n",
							"]x",
							"<cmd>lua require('diffview.actions').next_conflict()<CR>",
							{ desc = "Next conflict" },
						},
						{
							"n",
							"g?",
							"<cmd>lua require('diffview.actions').help('file_panel')<CR>",
							{ desc = "Show help" },
						},
						{
							"n",
							"<leader>cO",
							"<cmd>lua require('diffview.actions').conflict_choose_all('ours')<CR>",
							{ desc = "Choose all OURS" },
						},
						{
							"n",
							"<leader>cT",
							"<cmd>lua require('diffview.actions').conflict_choose_all('theirs')<CR>",
							{ desc = "Choose all THEIRS" },
						},
						{
							"n",
							"<leader>cB",
							"<cmd>lua require('diffview.actions').conflict_choose_all('base')<CR>",
							{ desc = "Choose all BASE" },
						},
						{
							"n",
							"<leader>cA",
							"<cmd>lua require('diffview.actions').conflict_choose_all('all')<CR>",
							{ desc = "Choose all ALL" },
						},
						{
							"n",
							"dX",
							"<cmd>lua require('diffview.actions').conflict_choose_all('none')<CR>",
							{ desc = "Delete all conflicts" },
						},
					},
					file_history_panel = {
						{
							"n",
							"g!",
							"<cmd>lua require('diffview.actions').options()<CR>",
							{ desc = "Options" },
						},
						{
							"n",
							"<C-A-d>",
							"<cmd>lua require('diffview.actions').open_in_diffview()<CR>",
							{ desc = "Open in diffview" },
						},
						{
							"n",
							"y",
							"<cmd>lua require('diffview.actions').copy_hash()<CR>",
							{ desc = "Copy commit hash" },
						},
						{
							"n",
							"L",
							"<cmd>lua require('diffview.actions').open_commit_log()<CR>",
							{ desc = "Open commit log" },
						},
						{
							"n",
							"X",
							"<cmd>lua require('diffview.actions').restore_entry()<CR>",
							{ desc = "Restore file" },
						},
						{
							"n",
							"zo",
							"<cmd>lua require('diffview.actions').open_fold()<CR>",
							{ desc = "Open fold" },
						},
						{
							"n",
							"zc",
							"<cmd>lua require('diffview.actions').close_fold()<CR>",
							{ desc = "Close fold" },
						},
						{
							"n",
							"h",
							"<cmd>lua require('diffview.actions').close_fold()<CR>",
							{ desc = "Close fold" },
						},
						{
							"n",
							"za",
							"<cmd>lua require('diffview.actions').toggle_fold()<CR>",
							{ desc = "Toggle fold" },
						},
						{
							"n",
							"zR",
							"<cmd>lua require('diffview.actions').open_all_folds()<CR>",
							{ desc = "Open all folds" },
						},
						{
							"n",
							"zM",
							"<cmd>lua require('diffview.actions').close_all_folds()<CR>",
							{ desc = "Close all folds" },
						},
						{
							"n",
							"j",
							"<cmd>lua require('diffview.actions').next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"<down>",
							"<cmd>lua require('diffview.actions').next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"k",
							"<cmd>lua require('diffview.actions').prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"<up>",
							"<cmd>lua require('diffview.actions').prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"<cr>",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"o",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"l",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"<2-LeftMouse>",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"<c-b>",
							"<cmd>lua require('diffview.actions').scroll_view(-0.25)<CR>",
							{ desc = "Scroll up" },
						},
						{
							"n",
							"<c-f>",
							"<cmd>lua require('diffview.actions').scroll_view(0.25)<CR>",
							{ desc = "Scroll down" },
						},
						{
							"n",
							"<tab>",
							"<cmd>lua require('diffview.actions').select_next_entry()<CR>",
							{ desc = "Next entry" },
						},
						{
							"n",
							"<s-tab>",
							"<cmd>lua require('diffview.actions').select_prev_entry()<CR>",
							{ desc = "Previous entry" },
						},
						{
							"n",
							"gf",
							"<cmd>lua require('diffview.actions').goto_file_edit()<CR>",
							{ desc = "Open file in current window" },
						},
						{
							"n",
							"<C-w><C-f>",
							"<cmd>lua require('diffview.actions').goto_file_split()<CR>",
							{ desc = "Open file in split" },
						},
						{
							"n",
							"<C-w>gf",
							"<cmd>lua require('diffview.actions').goto_file_tab()<CR>",
							{ desc = "Open file in new tab" },
						},
						{
							"n",
							"<leader>df",
							"<cmd>lua require('diffview.actions').focus_files()<CR>",
							{ desc = "Focus file panel" },
						},
						{
							"n",
							"<leader>b",
							"<cmd>lua require('diffview.actions').toggle_files()<CR>",
							{ desc = "Toggle file panel" },
						},
						{
							"n",
							"g<C-x>",
							"<cmd>lua require('diffview.actions').cycle_layout()<CR>",
							{ desc = "Cycle layout" },
						},
						{
							"n",
							"g?",
							"<cmd>lua require('diffview.actions').help('file_history_panel')<CR>",
							{ desc = "Show help" },
						},
					},
					option_panel = {
						{
							"n",
							"<tab>",
							"<cmd>lua require('diffview.actions').select_entry()<CR>",
							{ desc = "Select entry" },
						},
						{
							"n",
							"q",
							"<cmd>lua require('diffview.actions').close()<CR>",
							{ desc = "Close panel" },
						},
						{
							"n",
							"g?",
							"<cmd>lua require('diffview.actions').help('option_panel')<CR>",
							{ desc = "Show help" },
						},
					},
					help_panel = {
						{ "n", "q", "<cmd>lua require('diffview.actions').close()<CR>", { desc = "Close help" } },
					},
				},
			})
		end,
	},
}
