name: Main Verify

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Lua
        run: brew install lua

      - name: Run repo verification
        run: ./bin/executable_dotctl test
